### ISSUE TITLE
Unable to parse cucumber json report

### ISSUE THREAD

**Issue by ShanWehttam** [wearefriday/pumpkin#10]
Awesome tool.
I would have created a PR but i had permission issues from my personal github acc.  The only way i managed to get this program to work locally with Adams cucumber Json report was to make the following changes.

**As is**: next unless feature["name"] == feature_name  # feature['name'] key can't be found
**To be**:  next unless feature["elements"][0]["name"] == scenario_name

**As is:** @status_types = ["Not run","Descoped", "In Progress", "Passed", "Failed", "Blocked"]
**To be:** @status_types = ["Not run","Descoped", "In Progress", "passed", "Failed", "Blocked"]

ruby pumpkin.rb -f /Users/matthew.nash/pumpkin -c /Users/matthew.nash/pumpkin/cucumber_report.json

**Comment by nickdunn** [comment]
@ShanWehttam I think these are now fixed

https://github.com/wearefriday/pumpkin/commit/03638801da2a63cb9111de8316833398098fd535
